"""initial_schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-10-01 16:36:38.096345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('period_months', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('period_months > 0', name=op.f('ck_analyses_period_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_analyses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses'))
    )
    op.create_index(op.f('ix_analyses_user_id'), 'analyses', ['user_id'], unique=False)
    op.create_table('clusters',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('cluster_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_clusters_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clusters')),
    sa.UniqueConstraint('analysis_id', 'cluster_number', name='uq_clusters_analysis_number')
    )
    op.create_index(op.f('ix_clusters_analysis_id'), 'clusters', ['analysis_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint('price >= 0', name=op.f('ck_products_price_nonnegative')),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_products_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_analysis_id'), 'products', ['analysis_id'], unique=False)
    op.create_table('trend_points',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_trend_points_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trend_points')),
    sa.UniqueConstraint('analysis_id', 'date', name='uq_trend_points_analysis_date')
    )
    op.create_index(op.f('ix_trend_points_analysis_id'), 'trend_points', ['analysis_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('opportunity_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estimated_roi', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('estimated_margin', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('competition_level', sa.String(length=32), nullable=True),
    sa.Column('trend_type', sa.String(length=32), nullable=True),
    sa.CheckConstraint('opportunity_score BETWEEN 0 AND 100', name=op.f('ck_opportunities_score_range')),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_opportunities_analysis_id_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], name=op.f('fk_opportunities_cluster_id_clusters'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities'))
    )
    op.create_index(op.f('ix_opportunities_analysis_id'), 'opportunities', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_opportunities_cluster_id'), 'opportunities', ['cluster_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('product_name', sa.String(length=160), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('style', sa.String(length=40), nullable=False),
    sa.Column('scene', sa.String(length=300), nullable=False),
    sa.Column('lighting', sa.String(length=40), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=8), nullable=False),
    sa.Column('original_image_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_campaigns_opportunity_id_opportunities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_campaigns_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index(op.f('ix_campaigns_opportunity_id'), 'campaigns', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_campaigns_user_id'), 'campaigns', ['user_id'], unique=False)
    op.create_table('generated_assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_generated_assets_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_assets'))
    )
    op.create_index(op.f('ix_generated_assets_campaign_id'), 'generated_assets', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_assets_campaign_id'), table_name='generated_assets')
    op.drop_table('generated_assets')
    op.drop_index(op.f('ix_campaigns_user_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_opportunity_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_opportunities_cluster_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_analysis_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_trend_points_analysis_id'), table_name='trend_points')
    op.drop_table('trend_points')
    op.drop_index(op.f('ix_products_analysis_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_clusters_analysis_id'), table_name='clusters')
    op.drop_table('clusters')
    op.drop_index(op.f('ix_analyses_user_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_table('users')
    # ### end Alembic commands ###
